spring.application.name=ms-pedidos

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-pedidos-db
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=create

# Exibir SQL gerado no console
spring.jpa.show-sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.int[1,100]}
